### ISSUE TITLE
1.19 Crash

### ISSUE THREAD

**Issue by TheaRTGGaming** [WolfieWaffle/Hardcore-Torches-Forge#28]
the 1.19 version crashed

Mod Version 2.5

Details:
	Mod File: hardcore_torches_forge-1.19-2.5.jar
	Failure message: Hardcore Torches (hardcore_torches) has failed to load correctly
		java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS
	Mod Version: 1.19-2.5
	Mod Issue URL: https://github.com/WolfieWaffle/Hardcore-Torches-Forge/issues
	Exception message: java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS
Stacktrace:
	at com.github.wolfiewaffle.hardcore_torches.MainMod.<clinit>(MainMod.java:101) ~[hardcore_torches_forge-1.19-2.5.jar%23175!/:1.19-2.5] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.100.jar%23209!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.100.jar%23208!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by WolfieWaffle** [comment]
I think this might be a forge version mismatch. my version in my IDE appears to be  1.19-41.0.45. What forge version are you using?

**Comment by TheaRTGGaming** [comment]
1.19-41.0.100

**Comment by TheaRTGGaming** [comment]
Also here is the mod list I used

Mod List: 
		HudCompass-1.19-0.5.6.jar                         |HUD Compass                   |hudcompass                    |0.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		notenoughcrashes-4.1.7+1.19-forge.jar             |Not Enough Crashes            |notenoughcrashes              |4.1.7+1.19          |COMMON_SET|Manifest: NOSIGNATURE
		cgm-1.2.8-1.19.jar                                |MrCrayfish's Gun Mod          |cgm                           |1.2.8               |COMMON_SET|Manifest: NOSIGNATURE
		areas_1.19.0-3.0.jar                              |Areas                         |areas                         |3.0                 |COMMON_SET|Manifest: NOSIGNATURE
		EasyMagic-v4.0.0-1.19-Forge.jar                   |Easy Magic                    |easymagic                     |4.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.19-forge-11.0.0.225.jar                     |Just Enough Items             |jei                           |11.0.0.225          |COMMON_SET|Manifest: NOSIGNATURE
		UniversalBoneMeal-v4.0.1-1.19-Forge.jar           |Universal Bone Meal           |universalbonemeal             |4.0.1               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		TNTStickVanillaPlus-v1.2.2-1.19.jar               |TNT Stick VanillaPlus         |tntstickvanillaplus           |1.2.1               |ERROR     |Manifest: NOSIGNATURE
		caelus-forge-1.19-3.0.0.3.jar                     |Caelus API                    |caelus                        |1.19-3.0.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19-0.3.9.63.jar               |Sophisticated Core            |sophisticatedcore             |1.19-0.3.9.63       |COMMON_SET|Manifest: NOSIGNATURE
		reap-1.19-1.0.1.jar                               |Reap Mod                      |reap                          |1.19-1.0.1          |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.19-10.0.3.0-build.0499.jar       |ForgeEndertech                |forgeendertech                |10.0.3.0            |COMMON_SET|Manifest: NOSIGNATURE
		AdFinders-1.19-8.0.2.0-build.0499.jar             |Advanced Finders              |adfinders                     |8.0.2.0             |COMMON_SET|Manifest: NOSIGNATURE
		darkness-forge-mc119-2.0.95.jar                   |True Darkness                 |darkness                      |2.0.95              |ERROR     |Manifest: NOSIGNATURE
		JRFTL [1.19]-1.4.1.jar                            |JRFTL                         |jrftl                         |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.5.8_mc1.19.jar           |EnhancedVisuals               |enhancedvisuals               |1.5.8               |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.19-8.0.0.19.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		configured-1.5.5-1.19.jar                         |Configured                    |configured                    |1.5.5               |COMMON_SET|Manifest: NOSIGNATURE
		LibX-1.19-4.0.7.jar                               |LibX                          |libx                          |1.19-4.0.7          |COMMON_SET|Manifest: NOSIGNATURE
		hiddenrecipebook_1.19.0-2.5.jar                   |Hidden Recipe Book            |hiddenrecipebook              |2.5                 |COMMON_SET|Manifest: NOSIGNATURE
		worldborder_1.19.0-2.8.jar                        |World Border                  |worldborder                   |2.8                 |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.17.13.628.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.17.13.628    |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.1.jar                     |Guard Villagers               |guardvillagers                |1.19-1.5.1          |COMMON_SET|Manifest: NOSIGNATURE
		ActuallyUsefulSmithingTable-4.0.1 mc 1.19.X.jar   |Actually Useful Smithing Table|actuallyusefulsmithingtable   |4.0.1 mc 1.19.X     |COMMON_SET|Manifest: NOSIGNATURE
		catalogue-1.6.3-1.19.jar                          |Catalogue                     |catalogue                     |1.6.3               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-7.0.73-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.73              |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.19-1.0.9.jar                 |Sound Physics Remastered      |sound_physics_remastered      |1.19-1.0.9          |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.0.100-universal.jar                 |Forge                         |forge                         |41.0.100            |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[1.19] More Crafting Tables Forge 4.0.0.jar       |More Crafting Tables Mod      |mctb                          |1.19                |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		theoneprobe-1.19-6.2.0.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.0          |COMMON_SET|Manifest: NOSIGNATURE
		physics-mod-2.7.6-mc-1.19-forge.jar               |Physics Mod                   |physicsmod                    |2.7.6               |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.1_mc1.19.jar             |Ambient Sounds                |ambientsounds                 |5.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.7.4_mc1.19.jar              |CreativeCore                  |creativecore                  |2.7.4               |COMMON_SET|Manifest: NOSIGNATURE
		Amplified_Nether_v1.2.jar                         |Amplified Nether              |amplified_nether              |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		AdLods-1.19-7.0.2.0-build.0499.jar                |Large Ore Deposits            |adlods                        |7.0.2.0             |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |COMMON_SET|Manifest: NOSIGNATURE
		ObsidianBoat-1.9.0-build.18+mc1.19.jar            |Obsidian Boat                 |obsidianboat                  |1.9.0-build.18+mc1.1|COMMON_SET|Manifest: NOSIGNATURE
		ThisRocks-1.19-1.2.1.jar                          |This Rocks! (Forge)           |rocks                         |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		portablemobs-1.1.0a-forge-mc1.19.jar              |Portable Mobs                 |portablemobs                  |1.1.0a              |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.19-1.5.jar                        |betterfpsdist mod             |betterfpsdist                 |1.19-1.5            |COMMON_SET|Manifest: NOSIGNATURE
		pipez-1.19-1.0.6.jar                              |Pipez                         |pipez                         |1.19-1.0.6          |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.4.jar                     |Curios API                    |curios                        |1.19-5.1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19-FORGE-2.0.8.jar                    |Croptopia                     |croptopia                     |2.0.8               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.30.jar                        |Collective                    |collective                    |4.30                |COMMON_SET|Manifest: NOSIGNATURE
		hardcore_torches_forge-1.19-2.5.jar               |Hardcore Torches              |hardcore_torches              |1.19-2.5            |ERROR     |Manifest: NOSIGNATURE
		ToughAsNails-1.19-8.0.0.78.jar                    |Tough As Nails                |toughasnails                  |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		SimplyTools-1.19-1.0.4.jar                        |Simply Tools                  |simplytools                   |1.19-1.0.4          |COMMON_SET|Manifest: NOSIGNATURE
		randomvillagenames_1.19.0-1.8.jar                 |Random Village Names          |randomvillagenames            |1.8                 |COMMON_SET|Manifest: NOSIGNATURE
		DoubleSlabs-1.19-6.1.0.jar                        |Double Slabs                  |doubleslabs                   |6.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		tombstone-8.0.4-1.19.jar                          |Corail Tombstone              |tombstone                     |8.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		passiveshield_1.19.0-2.2.jar                      |Passive Shield                |passiveshield                 |2.2                 |COMMON_SET|Manifest: NOSIGNATURE
		mcw-roofs-2.1.2-mc1.19.jar                        |Macaw's Roofs                 |mcwroofs                      |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		pmmo-1.19-0.2.2.jar                               |Project MMO                   |pmmo                          |1.19-0.2.2          |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre33-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre33         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.9.31-forge.jar                     |Architectury                  |architectury                  |5.9.31              |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		light-overlay-7.0.1-forge.jar                     |Light Overlay                 |lightoverlay                  |7.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		DamageTilt-1.19-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v4.0.11-1.19-Forge.jar                 |Puzzles Lib                   |puzzleslib                    |4.0.11              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		parry-2.4.jar                                     |Shield Parry                  |parry                         |2.4                 |COMMON_SET|Manifest: NOSIGNATURE
		charmofundying-forge-6.0.0-beta.2+1.19.jar        |Charm of Undying              |charmofundying                |6.0.0-beta.2+1.19   |COMMON_SET|Manifest: NOSIGNATURE
		Aquaculture-1.19-2.4.4.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.4          |COMMON_SET|Manifest: NOSIGNATURE
		AdChimneys-1.19-9.1.3.0-build.0499.jar            |Advanced Chimneys             |adchimneys                    |9.1.3.0             |COMMON_SET|Manifest: NOSIGNATURE
		framework-0.3.2-1.19.jar                          |Framework                     |framework                     |0.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		BetterModsButton-v4.0.0-1.19-Forge.jar            |Better Mods Button            |bettermodsbutton              |4.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
